language: r
cache: packages
r:
    - release
    - devel 
os:
    - linux
    - osx
matrix:
    exclude:
        r: devel
        os: osx
sudo: false
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
r_github_packages: trevorld/piecepackr
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'
addons:
    apt:
       packages:
            - lmodern
            - texlive-xetex
