language: r
cache: packages
r:
    - release
    - devel 
os:
    - linux
    - osx
matrix:
    exclude:
        r: devel
        os: osx
sudo: false
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'lintr::lint_package()'
#   - Rscript -e 'covr::codecov()'
addons:
    apt:
       packages:
            - libmagick++-dev
            - lmodern
            - texlive-math-extra
            - texlive-xetex
r_github_packages:
  - jimhester/lintr
# - r-lib/covr
  - trevorld/piecepackr
