library("tibble")
context("test unicode")
test_that("dimensions", {
    df <- df_four_field_kono()
    expect_equal(range_heuristic(df)$xmin, 0.5)
    expect_equal(range_heuristic(df)$xmax, 4.5)
    expect_equal(range_heuristic(df)$ymin, 0.5)
    expect_equal(range_heuristic(df)$ymax, 4.5)
})
test_that("text diagrams", {
    skip_on_appveyor()
    expect_warning(rotate("$", 90))
    expect_warning(rotate("&", 180))
    expect_warning(rotate("&", 270))
    expect_warning(rotate("&", 45))
})
